version: 1
reporting: checks-v1
policy:
  pullRequests: public
tasks:
  $let:
    owner: taskcluster-internal@mozilla.com

    # This only supports pushes and pull requests for now.
    # If we start responding to another action type, make this
    # a $match.
    repo:
      $if: 'tasks_for == "github-push"'
      then:
        url: ${event.repository.url}
        ref: ${event.after}
      else:
        url: ${event.pull_request.head.repo.html_url}
        ref: ${event.pull_request.head.sha}
  in:
    $let:
      environments:
        - image: node:15
          name: node:15 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd js &&
              yarn &&
              yarn test
        - image: node:12
          name: node:12 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd js &&
              yarn &&
              yarn test
        - image: 'node:15'
          name: node import test
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd js &&
              yarn &&
              bash package-test.sh
        - image: 'python:3.8'
          name: python:3.8 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd py/ &&
              pip install tox &&
              tox -e py38
        - image: 'python:3.9'
          name: python:3.9 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd py/ &&
              pip install tox &&
              tox -e py39
        - image: 'python:3.10'
          name: python:3.10 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd py/ &&
              pip install tox &&
              tox -e py310
        - image: 'python:3.11'
          name: python:3.11 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd py/ &&
              pip install tox &&
              tox -e py311
        - image: 'python:3.12'
          name: python:3.12 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd py/ &&
              pip install tox &&
              tox -e py312
        - image: 'python:3.13'
          name: python:3.13 tests
          command:
            - /bin/bash
            - '--login'
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd py/ &&
              pip install tox &&
              tox -e py313
        - image: 'golangci/golangci-lint'
          name: golang lint and tests
          command:
            - /bin/bash
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              go get -v -d -t ./... &&
              go test -v -race ./... &&
              golangci-lint run
        - image: 'rust:latest'
          name: rust tests
          command:
            - /bin/bash
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              cd rs/ &&
              cargo test
        - image: 'rust:latest'
          name: mdbook tests
          command:
            - /bin/bash
            - '-c'
            - >-
              git clone ${repo.url} repo &&
              cd repo &&
              git config advice.detachedHead false &&
              git checkout ${repo.ref} &&
              curl -ssL https://github.com/rust-lang/mdBook/releases/download/v0.4.15/mdbook-v0.4.15-x86_64-unknown-linux-gnu.tar.gz | tar -zxf - &&
              ./mdbook test
    in:
      $let:
        tests:
          $map: {$eval: environments}
          each(env):
            taskId: {$eval: as_slugid(env.name)}
            provisionerId: proj-taskcluster
            workerType: ci
            created: {$fromNow: ''}
            deadline: {$fromNow: '60 minutes'}
            payload:
              maxRunTime: 3600
              image: ${env.image}
              command: {$eval: 'env.command'}
            metadata:
              name: ${env.name}
              description: ${env.name}
              owner: ${owner}
              source: ${repo.url}

      in:
        $flattenDeep:
        - $if: 'tasks_for == "github-push"'
          then: {$eval: tests}
        - $if: 'tasks_for == "github-pull-request" && event["action"] in ["opened", "reopened", "synchronize"]'
          then:
            # We can skip this if pushed to our own repo since push event will get it
            $if: 'event.pull_request.base.repo.id != event.pull_request.head.repo.id'
            then: {$eval: tests}
